name: CTT Exercise

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: .NET SDK install
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore packages
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
    
      - name: Clean .NET Environment
        uses: ./.github/actions/clear-environment

      - name: Run tests
        run: dotnet test tests/CTTExercise.Tests --logger "trx;LogFileName=test-results.trx"
        continue-on-error: true

      - name: Publish test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: tests/CTTExercise.Tests/TestResults/*.trx
          if-no-files-found: warn

  generate-test-reports:
    runs-on: ubuntu-latest
    if: always()
    needs: tests
    permissions:
      contents: read
      actions: read
      checks: write
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          pattern: TestResults_*
          merge-multiple: true
          run-id: ${{ github.event.workflow_run.id }}

      - name: Generate report
        uses: dorny/test-reporter@v1
        with:
          name: test-reports
          path: "**/TestResults/*.trx" 
          reporter: dotnet-trx